spring.application.name=mongo-test
logging.level.org.springframework.boot.testcontainers=INFO
logging.level.org.testcontainers=INFO
logging.level.com.sparta.spring_7_reactive.mongo=DEBUG

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.test.web.reactive.server=DEBUG
