spring.application.name=mongo
spring.data.mongodb.username=root
spring.data.mongodb.password=example
spring.data.mongodb.database=admin
spring.data.mongodb.host=localhost
#logging level
logging.level.com.sparta.spring_7_reactive.mongo=DEBUG
# security
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000
